/* tslint:disable */
/* eslint-disable */
/**
 * Diplomatiq API
 * This is the OpenAPI documentation of the Diplomatiq API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    DiplomatiqApiError,
    DiplomatiqApiErrorFromJSON,
    DiplomatiqApiErrorToJSON,
    LoginV1Response,
    LoginV1ResponseFromJSON,
    LoginV1ResponseToJSON,
} from '../models';

/**
 * no description
 */
export class AuthenticationSessionMethodsMultiFactorElevatedSessionApi extends runtime.BaseAPI {

    /**
     * Logs in the user on the current client device. Registers the client device, and issues request signing and authentication credentials for that client device.
     * Log in from a device
     */
    async loginV1Raw(): Promise<runtime.ApiResponse<LoginV1Response>> {
        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["AuthenticationSessionId"] = this.configuration.apiKey("AuthenticationSessionId"); // AuthenticationSessionId authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Authorization authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["ClientId"] = this.configuration.apiKey("ClientId"); // ClientId authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Instant"] = this.configuration.apiKey("Instant"); // Instant authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["SignedHeaders"] = this.configuration.apiKey("SignedHeaders"); // SignedHeaders authentication
        }

        const response = await this.request({
            path: `/login-v1`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => LoginV1ResponseFromJSON(jsonValue));
    }

    /**
     * Logs in the user on the current client device. Registers the client device, and issues request signing and authentication credentials for that client device.
     * Log in from a device
     */
    async loginV1(): Promise<LoginV1Response> {
        const response = await this.loginV1Raw();
        return await response.value();
    }

}
