/* tslint:disable */
/* eslint-disable */
/**
 * Diplomatiq API
 * This is the OpenAPI documentation of the Diplomatiq API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetDeviceContainerKeyV1Response
 */
export interface GetDeviceContainerKeyV1Response {
    /**
     * The key of the device container with the given ID.
     * @type {string}
     * @memberof GetDeviceContainerKeyV1Response
     */
    deviceContainerKeyBase64: string;
}

export function GetDeviceContainerKeyV1ResponseFromJSON(json: any): GetDeviceContainerKeyV1Response {
    return GetDeviceContainerKeyV1ResponseFromJSONTyped(json, false);
}

export function GetDeviceContainerKeyV1ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetDeviceContainerKeyV1Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'deviceContainerKeyBase64': json['deviceContainerKeyBase64'],
    };
}

export function GetDeviceContainerKeyV1ResponseToJSON(value?: GetDeviceContainerKeyV1Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'deviceContainerKeyBase64': value.deviceContainerKeyBase64,
    };
}


