/* tslint:disable */
/* eslint-disable */
/**
 * Diplomatiq API
 * This is the OpenAPI documentation of the Diplomatiq API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetSessionV1Request
 */
export interface GetSessionV1Request {
    /**
     * The session token, encrypted with the device key, as a Base64 string (in DiplomatiqAEAD format = AES-GCM without padding, serialized to binary `[1-byte ivLength | 4-byte aadLength (big-endian) | 4-byte ciphertextLength (big-endian) | 1-byte tagLength | ivLength-byte initialization vector | aadLength-byte additional authenticated data | ciphertextLength-byte ciphertext | tagLength-byte authentication tag]`)
     * @type {string}
     * @memberof GetSessionV1Request
     */
    sessionTokenAeadBase64: string;
}

export function GetSessionV1RequestFromJSON(json: any): GetSessionV1Request {
    return GetSessionV1RequestFromJSONTyped(json, false);
}

export function GetSessionV1RequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetSessionV1Request {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'sessionTokenAeadBase64': json['sessionTokenAeadBase64'],
    };
}

export function GetSessionV1RequestToJSON(value?: GetSessionV1Request | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'sessionTokenAeadBase64': value.sessionTokenAeadBase64,
    };
}


