/* tslint:disable */
/* eslint-disable */
/**
 * Diplomatiq API
 * This is the OpenAPI documentation of the Diplomatiq API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetSessionV1Response
 */
export interface GetSessionV1Response {
    /**
     * The ID of the created session or the ID of the old session which is still valid for at least 1 minute, as UTF-8 bytes, encrypted with the device key, as a Base64 string (in DiplomatiqAEAD format = AES-GCM without padding, serialized to binary `[1-byte ivLength | 4-byte aadLength (big-endian) | 4-byte ciphertextLength (big-endian) | 1-byte tagLength | ivLength-byte initialization vector | aadLength-byte additional authenticated data | ciphertextLength-byte ciphertext | tagLength-byte authentication tag]`)
     * @type {string}
     * @memberof GetSessionV1Response
     */
    sessionIdAeadBase64: string;
}

export function GetSessionV1ResponseFromJSON(json: any): GetSessionV1Response {
    return GetSessionV1ResponseFromJSONTyped(json, false);
}

export function GetSessionV1ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetSessionV1Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'sessionIdAeadBase64': json['sessionIdAeadBase64'],
    };
}

export function GetSessionV1ResponseToJSON(value?: GetSessionV1Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'sessionIdAeadBase64': value.sessionIdAeadBase64,
    };
}


