/* tslint:disable */
/* eslint-disable */
/**
 * Diplomatiq API
 * This is the OpenAPI documentation of the Diplomatiq API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RegisterUserV1Request
 */
export interface RegisterUserV1Request {
    /**
     * The email address of the user, it will be stored as its lowercase invariant!
     * @type {string}
     * @memberof RegisterUserV1Request
     */
    emailAddress: string;
    /**
     * The first name(s) of the user
     * @type {string}
     * @memberof RegisterUserV1Request
     */
    firstName: string;
    /**
     * The last name(s) of the user
     * @type {string}
     * @memberof RegisterUserV1Request
     */
    lastName: string;
    /**
     * The SRP salt (s) as a Hex string
     * @type {string}
     * @memberof RegisterUserV1Request
     */
    srpSaltHex: string;
    /**
     * The SRP verifier (s) as a Hex string
     * @type {string}
     * @memberof RegisterUserV1Request
     */
    srpVerifierHex: string;
    /**
     * The hash function used for calculating the exponent of the SRP verifier (v)
     * @type {string}
     * @memberof RegisterUserV1Request
     */
    passwordStretchingAlgorithm: RegisterUserV1RequestPasswordStretchingAlgorithmEnum;
}

export function RegisterUserV1RequestFromJSON(json: any): RegisterUserV1Request {
    return RegisterUserV1RequestFromJSONTyped(json, false);
}

export function RegisterUserV1RequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegisterUserV1Request {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'emailAddress': json['emailAddress'],
        'firstName': json['firstName'],
        'lastName': json['lastName'],
        'srpSaltHex': json['srpSaltHex'],
        'srpVerifierHex': json['srpVerifierHex'],
        'passwordStretchingAlgorithm': json['passwordStretchingAlgorithm'],
    };
}

export function RegisterUserV1RequestToJSON(value?: RegisterUserV1Request | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'emailAddress': value.emailAddress,
        'firstName': value.firstName,
        'lastName': value.lastName,
        'srpSaltHex': value.srpSaltHex,
        'srpVerifierHex': value.srpVerifierHex,
        'passwordStretchingAlgorithm': value.passwordStretchingAlgorithm,
    };
}

/**
* @export
* @enum {string}
*/
export enum RegisterUserV1RequestPasswordStretchingAlgorithmEnum {
    ScryptV1 = 'Scrypt_v1'
}


