/* tslint:disable */
/* eslint-disable */
/**
 * Diplomatiq API
 * This is the OpenAPI documentation of the Diplomatiq API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RequestPasswordResetV1Request
 */
export interface RequestPasswordResetV1Request {
    /**
     * The email address of the user
     * @type {string}
     * @memberof RequestPasswordResetV1Request
     */
    emailAddress: string;
}

export function RequestPasswordResetV1RequestFromJSON(json: any): RequestPasswordResetV1Request {
    return RequestPasswordResetV1RequestFromJSONTyped(json, false);
}

export function RequestPasswordResetV1RequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestPasswordResetV1Request {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'emailAddress': json['emailAddress'],
    };
}

export function RequestPasswordResetV1RequestToJSON(value?: RequestPasswordResetV1Request | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'emailAddress': value.emailAddress,
    };
}


