/* tslint:disable */
/* eslint-disable */
/**
 * Diplomatiq API
 * This is the OpenAPI documentation of the Diplomatiq API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ValidateEmailAddressV1Request
 */
export interface ValidateEmailAddressV1Request {
    /**
     * The email validation key the user received in email
     * @type {string}
     * @memberof ValidateEmailAddressV1Request
     */
    emailValidationKey: string;
}

export function ValidateEmailAddressV1RequestFromJSON(json: any): ValidateEmailAddressV1Request {
    return ValidateEmailAddressV1RequestFromJSONTyped(json, false);
}

export function ValidateEmailAddressV1RequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ValidateEmailAddressV1Request {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'emailValidationKey': json['emailValidationKey'],
    };
}

export function ValidateEmailAddressV1RequestToJSON(value?: ValidateEmailAddressV1Request | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'emailValidationKey': value.emailValidationKey,
    };
}


