/* tslint:disable */
/* eslint-disable */
/**
 * Diplomatiq API
 * This is the OpenAPI documentation of the Diplomatiq API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CancelApplicationV1Request
 */
export interface CancelApplicationV1Request {
    /**
     * The ID of the committee seat to cancel the application of
     * @type {string}
     * @memberof CancelApplicationV1Request
     */
    committeeSeatId: string;
}

export function CancelApplicationV1RequestFromJSON(json: any): CancelApplicationV1Request {
    return CancelApplicationV1RequestFromJSONTyped(json, false);
}

export function CancelApplicationV1RequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CancelApplicationV1Request {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'committeeSeatId': json['committeeSeatId'],
    };
}

export function CancelApplicationV1RequestToJSON(value?: CancelApplicationV1Request | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'committeeSeatId': value.committeeSeatId,
    };
}


