/* tslint:disable */
/* eslint-disable */
/**
 * Diplomatiq API
 * This is the OpenAPI documentation of the Diplomatiq API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CancelConferenceV1Request
 */
export interface CancelConferenceV1Request {
    /**
     * The ID of the conference to cancel
     * @type {string}
     * @memberof CancelConferenceV1Request
     */
    conferenceId: string;
}

export function CancelConferenceV1RequestFromJSON(json: any): CancelConferenceV1Request {
    return CancelConferenceV1RequestFromJSONTyped(json, false);
}

export function CancelConferenceV1RequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CancelConferenceV1Request {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'conferenceId': json['conferenceId'],
    };
}

export function CancelConferenceV1RequestToJSON(value?: CancelConferenceV1Request | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'conferenceId': value.conferenceId,
    };
}


