/* tslint:disable */
/* eslint-disable */
/**
 * Diplomatiq API
 * This is the OpenAPI documentation of the Diplomatiq API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChangePasswordV1Request
 */
export interface ChangePasswordV1Request {
    /**
     * The SRP salt (s) as a Hex string
     * @type {string}
     * @memberof ChangePasswordV1Request
     */
    srpSaltHex: string;
    /**
     * The SRP verifier (s) as a Hex string
     * @type {string}
     * @memberof ChangePasswordV1Request
     */
    srpVerifierHex: string;
    /**
     * The hash function used for calculating the exponent of the SRP verifier (v)
     * @type {string}
     * @memberof ChangePasswordV1Request
     */
    passwordStretchingAlgorithm: ChangePasswordV1RequestPasswordStretchingAlgorithmEnum;
}

export function ChangePasswordV1RequestFromJSON(json: any): ChangePasswordV1Request {
    return ChangePasswordV1RequestFromJSONTyped(json, false);
}

export function ChangePasswordV1RequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChangePasswordV1Request {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'srpSaltHex': json['srpSaltHex'],
        'srpVerifierHex': json['srpVerifierHex'],
        'passwordStretchingAlgorithm': json['passwordStretchingAlgorithm'],
    };
}

export function ChangePasswordV1RequestToJSON(value?: ChangePasswordV1Request | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'srpSaltHex': value.srpSaltHex,
        'srpVerifierHex': value.srpVerifierHex,
        'passwordStretchingAlgorithm': value.passwordStretchingAlgorithm,
    };
}

/**
* @export
* @enum {string}
*/
export enum ChangePasswordV1RequestPasswordStretchingAlgorithmEnum {
    ScryptV1 = 'Scrypt_v1'
}


