/* tslint:disable */
/* eslint-disable */
/**
 * Diplomatiq API
 * This is the OpenAPI documentation of the Diplomatiq API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EmptyCommitteeSeat,
    EmptyCommitteeSeatFromJSON,
    EmptyCommitteeSeatFromJSONTyped,
    EmptyCommitteeSeatToJSON,
} from './';

/**
 * The list of committees which have empty seats, with empty seats
 * @export
 * @interface CommitteeWithEmptySeats
 */
export interface CommitteeWithEmptySeats {
    /**
     * The name of the committee
     * @type {string}
     * @memberof CommitteeWithEmptySeats
     */
    name: string;
    /**
     * The code name of the committee
     * @type {string}
     * @memberof CommitteeWithEmptySeats
     */
    codeName: string;
    /**
     * The list of seats (represented countries) which are still empty
     * @type {Array<EmptyCommitteeSeat>}
     * @memberof CommitteeWithEmptySeats
     */
    emptyCommitteeSeats: Array<EmptyCommitteeSeat>;
}

export function CommitteeWithEmptySeatsFromJSON(json: any): CommitteeWithEmptySeats {
    return CommitteeWithEmptySeatsFromJSONTyped(json, false);
}

export function CommitteeWithEmptySeatsFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommitteeWithEmptySeats {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'codeName': json['codeName'],
        'emptyCommitteeSeats': ((json['emptyCommitteeSeats'] as Array<any>).map(EmptyCommitteeSeatFromJSON)),
    };
}

export function CommitteeWithEmptySeatsToJSON(value?: CommitteeWithEmptySeats | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'codeName': value.codeName,
        'emptyCommitteeSeats': ((value.emptyCommitteeSeats as Array<any>).map(EmptyCommitteeSeatToJSON)),
    };
}


