/* tslint:disable */
/* eslint-disable */
/**
 * Diplomatiq API
 * This is the OpenAPI documentation of the Diplomatiq API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    RetryInformation,
    RetryInformationFromJSON,
    RetryInformationFromJSONTyped,
    RetryInformationToJSON,
} from './';

/**
 * 
 * @export
 * @interface DiplomatiqApiError
 */
export interface DiplomatiqApiError {
    /**
     * The identifier of the error for client reactions
     * @type {string}
     * @memberof DiplomatiqApiError
     */
    errorCode: DiplomatiqApiErrorErrorCodeEnum;
    /**
     * 
     * @type {RetryInformation}
     * @memberof DiplomatiqApiError
     */
    retryInformation?: RetryInformation;
}

export function DiplomatiqApiErrorFromJSON(json: any): DiplomatiqApiError {
    return DiplomatiqApiErrorFromJSONTyped(json, false);
}

export function DiplomatiqApiErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): DiplomatiqApiError {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'errorCode': json['errorCode'],
        'retryInformation': !exists(json, 'retryInformation') ? undefined : RetryInformationFromJSON(json['retryInformation']),
    };
}

export function DiplomatiqApiErrorToJSON(value?: DiplomatiqApiError | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'errorCode': value.errorCode,
        'retryInformation': RetryInformationToJSON(value.retryInformation),
    };
}

/**
* @export
* @enum {string}
*/
export enum DiplomatiqApiErrorErrorCodeEnum {
    BadRequest = 'BadRequest',
    ClockDiscrepancy = 'ClockDiscrepancy',
    EmailAddressNotValidated = 'EmailAddressNotValidated',
    InternalServerError = 'InternalServerError',
    MethodNotAllowed = 'MethodNotAllowed',
    NotAcceptable = 'NotAcceptable',
    NotFound = 'NotFound',
    Unauthorized = 'Unauthorized',
    UnsupportedMediaType = 'UnsupportedMediaType'
}


