/* tslint:disable */
/* eslint-disable */
/**
 * Diplomatiq API
 * This is the OpenAPI documentation of the Diplomatiq API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ElevatePasswordElevatedSessionCompleteV1Request
 */
export interface ElevatePasswordElevatedSessionCompleteV1Request {
    /**
     * The multi-factor authentication code
     * @type {string}
     * @memberof ElevatePasswordElevatedSessionCompleteV1Request
     */
    requestCode: string;
}

export function ElevatePasswordElevatedSessionCompleteV1RequestFromJSON(json: any): ElevatePasswordElevatedSessionCompleteV1Request {
    return ElevatePasswordElevatedSessionCompleteV1RequestFromJSONTyped(json, false);
}

export function ElevatePasswordElevatedSessionCompleteV1RequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ElevatePasswordElevatedSessionCompleteV1Request {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'requestCode': json['requestCode'],
    };
}

export function ElevatePasswordElevatedSessionCompleteV1RequestToJSON(value?: ElevatePasswordElevatedSessionCompleteV1Request | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'requestCode': value.requestCode,
    };
}


