/* tslint:disable */
/* eslint-disable */
/**
 * Diplomatiq API
 * This is the OpenAPI documentation of the Diplomatiq API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ElevateRegularSessionCompleteV1Request
 */
export interface ElevateRegularSessionCompleteV1Request {
    /**
     * The SRP client ephemeral (A) as a Hex string
     * @type {string}
     * @memberof ElevateRegularSessionCompleteV1Request
     */
    clientEphemeralHex: string;
    /**
     * The SRP client proof (M1) as a Hex string
     * @type {string}
     * @memberof ElevateRegularSessionCompleteV1Request
     */
    clientProofHex: string;
    /**
     * The SRP server ephemeral (B) received previously, as a Hex string
     * @type {string}
     * @memberof ElevateRegularSessionCompleteV1Request
     */
    serverEphemeralHex: string;
}

export function ElevateRegularSessionCompleteV1RequestFromJSON(json: any): ElevateRegularSessionCompleteV1Request {
    return ElevateRegularSessionCompleteV1RequestFromJSONTyped(json, false);
}

export function ElevateRegularSessionCompleteV1RequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ElevateRegularSessionCompleteV1Request {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'clientEphemeralHex': json['clientEphemeralHex'],
        'clientProofHex': json['clientProofHex'],
        'serverEphemeralHex': json['serverEphemeralHex'],
    };
}

export function ElevateRegularSessionCompleteV1RequestToJSON(value?: ElevateRegularSessionCompleteV1Request | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'clientEphemeralHex': value.clientEphemeralHex,
        'clientProofHex': value.clientProofHex,
        'serverEphemeralHex': value.serverEphemeralHex,
    };
}


