/* tslint:disable */
/* eslint-disable */
/**
 * Diplomatiq API
 * This is the OpenAPI documentation of the Diplomatiq API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ElevateRegularSessionInitV1Response
 */
export interface ElevateRegularSessionInitV1Response {
    /**
     * The SRP server ephemeral (B) as a Hex string
     * @type {string}
     * @memberof ElevateRegularSessionInitV1Response
     */
    serverEphemeralHex: string;
    /**
     * The SRP salt (s) as a Hex string
     * @type {string}
     * @memberof ElevateRegularSessionInitV1Response
     */
    srpSaltHex: string;
    /**
     * The hash function used for calculating the exponent of the SRP verifier (v)
     * @type {string}
     * @memberof ElevateRegularSessionInitV1Response
     */
    passwordStretchingAlgorithm: ElevateRegularSessionInitV1ResponsePasswordStretchingAlgorithmEnum;
}

export function ElevateRegularSessionInitV1ResponseFromJSON(json: any): ElevateRegularSessionInitV1Response {
    return ElevateRegularSessionInitV1ResponseFromJSONTyped(json, false);
}

export function ElevateRegularSessionInitV1ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ElevateRegularSessionInitV1Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'serverEphemeralHex': json['serverEphemeralHex'],
        'srpSaltHex': json['srpSaltHex'],
        'passwordStretchingAlgorithm': json['passwordStretchingAlgorithm'],
    };
}

export function ElevateRegularSessionInitV1ResponseToJSON(value?: ElevateRegularSessionInitV1Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'serverEphemeralHex': value.serverEphemeralHex,
        'srpSaltHex': value.srpSaltHex,
        'passwordStretchingAlgorithm': value.passwordStretchingAlgorithm,
    };
}

/**
* @export
* @enum {string}
*/
export enum ElevateRegularSessionInitV1ResponsePasswordStretchingAlgorithmEnum {
    ScryptV1 = 'Scrypt_v1'
}


