/* tslint:disable */
/* eslint-disable */
/**
 * Diplomatiq API
 * This is the OpenAPI documentation of the Diplomatiq API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * The list of seats (represented countries) which are still empty
 * @export
 * @interface EmptyCommitteeSeat
 */
export interface EmptyCommitteeSeat {
    /**
     * The ID of the committee seat
     * @type {string}
     * @memberof EmptyCommitteeSeat
     */
    committeeSeatId: string;
    /**
     * The represented country as ISO3166 alpha2 country code
     * @type {string}
     * @memberof EmptyCommitteeSeat
     */
    representedCountry: string;
}

export function EmptyCommitteeSeatFromJSON(json: any): EmptyCommitteeSeat {
    return EmptyCommitteeSeatFromJSONTyped(json, false);
}

export function EmptyCommitteeSeatFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmptyCommitteeSeat {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'committeeSeatId': json['committeeSeatId'],
        'representedCountry': json['representedCountry'],
    };
}

export function EmptyCommitteeSeatToJSON(value?: EmptyCommitteeSeat | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'committeeSeatId': value.committeeSeatId,
        'representedCountry': value.representedCountry,
    };
}


