/* tslint:disable */
/* eslint-disable */
/**
 * Diplomatiq API
 * This is the OpenAPI documentation of the Diplomatiq API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetMyOrganizedConferencesV1Response
 */
export interface GetMyOrganizedConferencesV1Response {
    /**
     * The ID of the conference
     * @type {string}
     * @memberof GetMyOrganizedConferencesV1Response
     */
    conferenceId: string;
    /**
     * The full name of the conference
     * @type {string}
     * @memberof GetMyOrganizedConferencesV1Response
     */
    conferenceName: string;
    /**
     * The code name of the conference
     * @type {string}
     * @memberof GetMyOrganizedConferencesV1Response
     */
    conferenceCodeName: string;
    /**
     * The start date of the conference
     * @type {string}
     * @memberof GetMyOrganizedConferencesV1Response
     */
    conferenceFrom: string;
    /**
     * The end date of the conference
     * @type {string}
     * @memberof GetMyOrganizedConferencesV1Response
     */
    conferenceTo: string;
    /**
     * The country of the conference address as an ISO3166-1 alpha-2 two letter country code
     * @type {string}
     * @memberof GetMyOrganizedConferencesV1Response
     */
    conferenceCountry: string;
    /**
     * The city of the conference address
     * @type {string}
     * @memberof GetMyOrganizedConferencesV1Response
     */
    conferenceCity: string;
    /**
     * The address of the conference
     * @type {string}
     * @memberof GetMyOrganizedConferencesV1Response
     */
    conferenceAddress: string;
    /**
     * The postal code of the conference address
     * @type {string}
     * @memberof GetMyOrganizedConferencesV1Response
     */
    conferencePostalCode: string;
    /**
     * The number of committee seats which are applied by a user
     * @type {number}
     * @memberof GetMyOrganizedConferencesV1Response
     */
    filledCommitteeSeats: number;
    /**
     * The number of all announced committee seats of the conference
     * @type {number}
     * @memberof GetMyOrganizedConferencesV1Response
     */
    allCommitteeSeats?: number;
}

export function GetMyOrganizedConferencesV1ResponseFromJSON(json: any): GetMyOrganizedConferencesV1Response {
    return GetMyOrganizedConferencesV1ResponseFromJSONTyped(json, false);
}

export function GetMyOrganizedConferencesV1ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetMyOrganizedConferencesV1Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'conferenceId': json['conferenceId'],
        'conferenceName': json['conferenceName'],
        'conferenceCodeName': json['conferenceCodeName'],
        'conferenceFrom': json['conferenceFrom'],
        'conferenceTo': json['conferenceTo'],
        'conferenceCountry': json['conferenceCountry'],
        'conferenceCity': json['conferenceCity'],
        'conferenceAddress': json['conferenceAddress'],
        'conferencePostalCode': json['conferencePostalCode'],
        'filledCommitteeSeats': json['filledCommitteeSeats'],
        'allCommitteeSeats': !exists(json, 'allCommitteeSeats') ? undefined : json['allCommitteeSeats'],
    };
}

export function GetMyOrganizedConferencesV1ResponseToJSON(value?: GetMyOrganizedConferencesV1Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'conferenceId': value.conferenceId,
        'conferenceName': value.conferenceName,
        'conferenceCodeName': value.conferenceCodeName,
        'conferenceFrom': value.conferenceFrom,
        'conferenceTo': value.conferenceTo,
        'conferenceCountry': value.conferenceCountry,
        'conferenceCity': value.conferenceCity,
        'conferenceAddress': value.conferenceAddress,
        'conferencePostalCode': value.conferencePostalCode,
        'filledCommitteeSeats': value.filledCommitteeSeats,
        'allCommitteeSeats': value.allCommitteeSeats,
    };
}


