/* tslint:disable */
/* eslint-disable */
/**
 * Diplomatiq API
 * This is the OpenAPI documentation of the Diplomatiq API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetMyConferencesV1Response
 */
export interface GetMyConferencesV1Response {
    /**
     * The full name of the conference
     * @type {string}
     * @memberof GetMyConferencesV1Response
     */
    conferenceName: string;
    /**
     * The code name of the conference
     * @type {string}
     * @memberof GetMyConferencesV1Response
     */
    conferenceCodeName: string;
    /**
     * The start date of the conference
     * @type {string}
     * @memberof GetMyConferencesV1Response
     */
    conferenceFrom: string;
    /**
     * The end date of the conference
     * @type {string}
     * @memberof GetMyConferencesV1Response
     */
    conferenceTo: string;
    /**
     * The country of the conference address as an ISO3166-1 alpha-2 two letter country code
     * @type {string}
     * @memberof GetMyConferencesV1Response
     */
    conferenceCountry: string;
    /**
     * The city of the conference address
     * @type {string}
     * @memberof GetMyConferencesV1Response
     */
    conferenceCity: string;
    /**
     * The address of the conference
     * @type {string}
     * @memberof GetMyConferencesV1Response
     */
    conferenceAddress: string;
    /**
     * The postal code of the conference address
     * @type {string}
     * @memberof GetMyConferencesV1Response
     */
    conferencePostalCode: string;
    /**
     * The name of the committee the user represents in
     * @type {string}
     * @memberof GetMyConferencesV1Response
     */
    committeeName: string;
    /**
     * The code name of the committee the user represents in
     * @type {string}
     * @memberof GetMyConferencesV1Response
     */
    committeeCodeName: string;
    /**
     * The represented country of the user as an ISO3166-1 alpha-2 two letter country code
     * @type {string}
     * @memberof GetMyConferencesV1Response
     */
    representedCountry: string;
    /**
     * The ID of the represented committee seat
     * @type {string}
     * @memberof GetMyConferencesV1Response
     */
    committeeSeatId: string;
}

export function GetMyConferencesV1ResponseFromJSON(json: any): GetMyConferencesV1Response {
    return GetMyConferencesV1ResponseFromJSONTyped(json, false);
}

export function GetMyConferencesV1ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetMyConferencesV1Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'conferenceName': json['conferenceName'],
        'conferenceCodeName': json['conferenceCodeName'],
        'conferenceFrom': json['conferenceFrom'],
        'conferenceTo': json['conferenceTo'],
        'conferenceCountry': json['conferenceCountry'],
        'conferenceCity': json['conferenceCity'],
        'conferenceAddress': json['conferenceAddress'],
        'conferencePostalCode': json['conferencePostalCode'],
        'committeeName': json['committeeName'],
        'committeeCodeName': json['committeeCodeName'],
        'representedCountry': json['representedCountry'],
        'committeeSeatId': json['committeeSeatId'],
    };
}

export function GetMyConferencesV1ResponseToJSON(value?: GetMyConferencesV1Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'conferenceName': value.conferenceName,
        'conferenceCodeName': value.conferenceCodeName,
        'conferenceFrom': value.conferenceFrom,
        'conferenceTo': value.conferenceTo,
        'conferenceCountry': value.conferenceCountry,
        'conferenceCity': value.conferenceCity,
        'conferenceAddress': value.conferenceAddress,
        'conferencePostalCode': value.conferencePostalCode,
        'committeeName': value.committeeName,
        'committeeCodeName': value.committeeCodeName,
        'representedCountry': value.representedCountry,
        'committeeSeatId': value.committeeSeatId,
    };
}


