/* tslint:disable */
/* eslint-disable */
/**
 * Diplomatiq API
 * This is the OpenAPI documentation of the Diplomatiq API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetUserIdentityV1Response
 */
export interface GetUserIdentityV1Response {
    /**
     * The email address of the user
     * @type {string}
     * @memberof GetUserIdentityV1Response
     */
    emailAddress: string;
    /**
     * The first name of the user
     * @type {string}
     * @memberof GetUserIdentityV1Response
     */
    firstName: string;
    /**
     * The last name of the user
     * @type {string}
     * @memberof GetUserIdentityV1Response
     */
    lastName: string;
}

export function GetUserIdentityV1ResponseFromJSON(json: any): GetUserIdentityV1Response {
    return GetUserIdentityV1ResponseFromJSONTyped(json, false);
}

export function GetUserIdentityV1ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetUserIdentityV1Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'emailAddress': json['emailAddress'],
        'firstName': json['firstName'],
        'lastName': json['lastName'],
    };
}

export function GetUserIdentityV1ResponseToJSON(value?: GetUserIdentityV1Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'emailAddress': value.emailAddress,
        'firstName': value.firstName,
        'lastName': value.lastName,
    };
}


