/* tslint:disable */
/* eslint-disable */
/**
 * Diplomatiq API
 * This is the OpenAPI documentation of the Diplomatiq API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LoginV1Response
 */
export interface LoginV1Response {
    /**
     * The ID of the created device as UTF-8 bytes, encrypted with the device key, as a Base64 string (in DiplomatiqAEAD format = AES-GCM without padding, serialized to binary `[1-byte ivLength | 4-byte aadLength (big-endian) | 4-byte ciphertextLength (big-endian) | 1-byte tagLength | ivLength-byte initialization vector | aadLength-byte additional authenticated data | ciphertextLength-byte ciphertext | tagLength-byte authentication tag]`)
     * @type {string}
     * @memberof LoginV1Response
     */
    deviceIdAeadBase64: string;
    /**
     * The device key, encrypted with the authentication session key, as a Base64 string (in DiplomatiqAEAD format = AES-GCM without padding, serialized to binary `[1-byte ivLength | 4-byte aadLength (big-endian) | 4-byte ciphertextLength (big-endian) | 1-byte tagLength | ivLength-byte initialization vector | aadLength-byte additional authenticated data | ciphertextLength-byte ciphertext | tagLength-byte authentication tag]`)
     * @type {string}
     * @memberof LoginV1Response
     */
    deviceKeyAeadBase64: string;
    /**
     * The session token, encrypted with the device key, as a Base64 string (in DiplomatiqAEAD format = AES-GCM without padding, serialized to binary `[1-byte ivLength | 4-byte aadLength (big-endian) | 4-byte ciphertextLength (big-endian) | 1-byte tagLength | ivLength-byte initialization vector | aadLength-byte additional authenticated data | ciphertextLength-byte ciphertext | tagLength-byte authentication tag]`)
     * @type {string}
     * @memberof LoginV1Response
     */
    sessionTokenAeadBase64: string;
}

export function LoginV1ResponseFromJSON(json: any): LoginV1Response {
    return LoginV1ResponseFromJSONTyped(json, false);
}

export function LoginV1ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoginV1Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'deviceIdAeadBase64': json['deviceIdAeadBase64'],
        'deviceKeyAeadBase64': json['deviceKeyAeadBase64'],
        'sessionTokenAeadBase64': json['sessionTokenAeadBase64'],
    };
}

export function LoginV1ResponseToJSON(value?: LoginV1Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'deviceIdAeadBase64': value.deviceIdAeadBase64,
        'deviceKeyAeadBase64': value.deviceKeyAeadBase64,
        'sessionTokenAeadBase64': value.sessionTokenAeadBase64,
    };
}


