name: Build, test and publish to Azure

on:
    push:
        branches:
            - master

jobs:
    build-test-and-publish:
        name: 'Build, test and publish'
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
            - name: Set up Node.js version
              uses: actions/setup-node@v1
              with:
                  node-version: 13
            - name: Install dependencies
              run: npm ci
            - name: Lint the code
              run: npm run lint
            - name: Run unit tests
              run: npm run test-ci
            - name: Run end-to-end tests
              run: npm run e2e-ci
            - name: Prepare distribution deployment artefact
              run: npm run build-dist
            - name: Store distribution deployment artefact
              uses: actions/upload-artifact@v1
              with:
                  name: diplomatiq-frontend-dist-${{ github.sha }}
                  path: dist/diplomatiq-frontend
            - name: Publish distribution deployment artefact to Azure
              uses: azure/webapps-deploy@v1
              with:
                  app-name: 'app-diplomatiqfrontend-prod-001'
                  slot-name: 'production'
                  publish-profile: ${{ secrets.AzureAppService_PublishProfile_bb07b11d109e46e79b3d941ac9bb41c5 }}
                  package: 'dist/diplomatiq-frontend'
